# fullsend per-repo configuration
# https://github.com/fullsend-ai/fullsend
#
# This file configures fullsend for per-repo installation mode.
# See https://fullsend.sh/docs/guides/infrastructure/layered-config-reference
version: "1"
roles:
    - triage
    - coder
    - review
    - fix
    - retro
    - prioritize
agents:
    - name: triage
      model: claude-sonnet-5-5
    - name: retro
      source: https://raw.githubusercontent.com/fullsend-ai/agents/bf4dfb12b05342b43fa77d84943c6434efb1eaca/harness/retro.yaml#sha256=8be74d42aa94ed0083fd1a915f9903435d797b801b3866acd7e8249830388835
    - source: https://raw.githubusercontent.com/rh-hemartin/rfe-creator/3369f72f87470c67be8b9a7d0671dcbe92af1244/.fullsend/rfe-creator/rfe-creator.yaml#sha256=690b1c01ca825a717588974ea4dc931d2ee74091e7086a88cc2be745a00fff2b
      ref: testing-fullsend
      model: claude-sonnet-5-5
allowed_remote_resources:
    - https://raw.githubusercontent.com/rh-hemartin-fullsendai/standalone-fullsend/
    - https://raw.githubusercontent.com/fullsend-ai/agents/
    - https://raw.githubusercontent.com/fullsend-ai/fullsend/
    - https://raw.githubusercontent.com/rh-hemartin/rfe-creator/
create_issues:
    allow_targets:
        repos:
            - rh-hemartin-fullsendai/standalone-fullsend
            - fullsend-ai/fullsend
mint_url: https://mint.fullsend.sh
inference:
    project: team-adlc-on-fullsend
    wif_provider: projects/365777540927/locations/global/workloadIdentityPools/fullsend-inference/providers/gh-rh-hemartin-fullsendai-standa
