# fullsend per-repo configuration
# https://github.com/fullsend-ai/fullsend
#
# This file configures fullsend for per-repo installation mode.
# See ADR 0033 for details.
version: "1"
roles:
    - triage
    - coder
    - review
    - fix
    - retro
    - prioritize
    - qualityflow

agents:
  - name: code
    source: code.yaml
  - name: retro
    source: https://raw.githubusercontent.com/fullsend-ai/agents/bf4dfb12b05342b43fa77d84943c6434efb1eaca/harness/retro.yaml#sha256=8be74d42aa94ed0083fd1a915f9903435d797b801b3866acd7e8249830388835
  - name: qualityflow
    source: https://raw.githubusercontent.com/redhat-community-ai-tools/qualityflow-fullsend/a92589a/harness/qualityflow.yaml#sha256=9a75483e6791006b30dcdbe09bde0927a62f95e50469c8bffd7369f160dc271c
create_issues:
    allow_targets:
        repos:
            - rh-hemartin-fullsendai/standalone-fullsend
            - fullsend-ai/fullsend

allowed_remote_resources:
  - https://raw.githubusercontent.com/rh-hemartin-fullsendai/standalone-fullsend/
  - https://raw.githubusercontent.com/fullsend-ai/agents/
  - https://raw.githubusercontent.com/redhat-community-ai-tools/qualityflow-fullsend/
