#!/usr/bin/env bash
# post-retro.sh — File GitHub issues from retro agent proposals and post summary.
#
# Runs on the host after sandbox cleanup. Working directory is the fullsend
# run output directory.
#
# Required env vars:
#   ORIGINATING_URL — HTML URL of the originating PR or issue
#   GH_TOKEN        — GitHub token with issues:write and pull_requests:write scope
#
# The agent writes its result to output/agent-result.json (relative to
# the iteration directory). This script finds the most recent iteration's output.

set -euo pipefail

: "${ORIGINATING_URL:?ORIGINATING_URL is required}"
: "${GH_TOKEN:?GH_TOKEN is required}"
echo "::add-mask::${GH_TOKEN}"

# Find the retro result JSON (same pattern as post-triage.sh).
RESULT_FILE=""
for dir in iteration-*/output; do
  if [[ -f "${dir}/agent-result.json" ]]; then
    RESULT_FILE="${dir}/agent-result.json"
  fi
done

if [[ -z "${RESULT_FILE}" ]]; then
  echo "ERROR: agent-result.json not found in any iteration output directory" >&2
  exit 1
fi

echo "Reading retro result from: ${RESULT_FILE}"

# Validate JSON is parseable.
if ! jq empty "${RESULT_FILE}" 2>/dev/null; then
  echo "ERROR: ${RESULT_FILE} is not valid JSON" >&2
  exit 1
fi

# Extract repo and number from ORIGINATING_URL.
# Accepts both /issues/N and /pull/N.
if [[ ! "${ORIGINATING_URL}" =~ ^https://github\.com/[a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+/(issues|pull)/[0-9]+$ ]]; then
  echo "ERROR: ORIGINATING_URL does not match expected pattern: ${ORIGINATING_URL}" >&2
  exit 1
fi
ORIGINATING_REPO=$(echo "${ORIGINATING_URL}" | sed -E 's#https://github.com/##; s#/(issues|pull)/.*##')
ORIGINATING_NUMBER=$(basename "${ORIGINATING_URL}")

echo "Originating: ${ORIGINATING_REPO}#${ORIGINATING_NUMBER}"

# File an issue for each proposal.
PROPOSAL_COUNT=$(jq '.proposals | length' "${RESULT_FILE}")
echo "Found ${PROPOSAL_COUNT} proposal(s)"

# Validate all proposals before filing any to avoid partial state.
for i in $(seq 0 $((PROPOSAL_COUNT - 1))); do
  TR=$(jq -r ".proposals[$i].target_repo" "${RESULT_FILE}")
  if [[ ! "${TR}" =~ ^[a-zA-Z0-9._-]+/[a-zA-Z0-9._-]+$ ]]; then
    echo "ERROR: proposal[$i].target_repo is not a valid owner/repo: ${TR}" >&2
    exit 1
  fi
  TI=$(jq -r ".proposals[$i].title // empty" "${RESULT_FILE}")
  if [[ -z "${TI}" ]]; then
    echo "ERROR: proposal[$i].title is missing or empty" >&2
    exit 1
  fi
  jq -e ".proposals[$i] | .what_happened and .what_could_go_better and .proposed_change and .validation_criteria" "${RESULT_FILE}" >/dev/null 2>&1 || {
    echo "ERROR: proposal[$i] is missing required fields" >&2
    exit 1
  }
done
echo "All ${PROPOSAL_COUNT} proposal(s) validated"

ISSUE_LINKS=""
for i in $(seq 0 $((PROPOSAL_COUNT - 1))); do
  TARGET_REPO=$(jq -r ".proposals[$i].target_repo" "${RESULT_FILE}")
  TITLE=$(jq -r ".proposals[$i].title" "${RESULT_FILE}")

  # Build the issue body from the four sections.
  BODY=$(jq -r --arg url "${ORIGINATING_URL}" "
    .proposals[$i] |
    \"## What happened\n\n\" + .what_happened +
    \"\n\n## What could go better\n\n\" + .what_could_go_better +
    \"\n\n## Proposed change\n\n\" + .proposed_change +
    \"\n\n## Validation criteria\n\n\" + .validation_criteria +
    \"\n\n---\n_Generated by retro agent from \" + \$url + \"_\"
  " "${RESULT_FILE}")

  # TODO(#833): Remove this warning once per-repo customization is stable.
  # Depends on: #195, #179, #419, PR #792, PR #799.
  if [[ "${TARGET_REPO}" == */.fullsend ]]; then
    echo "::warning::proposal[$i] targets a .fullsend repo (${TARGET_REPO}). Filing in .fullsend repos is discouraged until per-repo customization patterns are stable. Consider filing in the source repo or fullsend-ai/fullsend upstream instead."
  fi

  # Ensure the label exists in the target repo before applying it.
  # Follows the same pattern as post-review.sh for ready-for-merge.
  # --force makes this idempotent (no error if the label already exists).
  gh label create "ready-for-triage" \
    --repo "${TARGET_REPO}" \
    --description "Retro-filed issue awaiting triage agent" \
    --color "ededed" \
    --force 2>/dev/null || true

  echo "Filing issue in ${TARGET_REPO}: ${TITLE}"
  if ! ISSUE_URL=$(gh issue create \
    --repo "${TARGET_REPO}" \
    --title "${TITLE}" \
    --body "${BODY}" \
    --label "ready-for-triage" 2>&1); then
    echo "ERROR: failed to create issue in ${TARGET_REPO} (gh issue create --repo ${TARGET_REPO}): ${ISSUE_URL}" >&2
    exit 1
  fi

  echo "Created: ${ISSUE_URL}"
  ISSUE_LINKS="${ISSUE_LINKS}- [${TITLE}](${ISSUE_URL}) (in \`${TARGET_REPO}\`)
"
done

# Post summary comment on the originating PR/issue.
# Uses REST API (not gh issue comment) for consistency. Note: despite being
# an "issues" endpoint, GitHub requires pull_requests:write when the target
# number is a PR. See https://github.com/orgs/community/discussions/26644
SUMMARY=$(jq -r '.summary // empty' "${RESULT_FILE}")
if [[ -z "${SUMMARY}" ]]; then
  echo "ERROR: .summary is missing or empty in agent result" >&2
  exit 1
fi

if [[ "${PROPOSAL_COUNT}" -gt 0 ]]; then
  COMMENT=$(printf '%s\n\n### Proposals filed\n\n%s' "${SUMMARY}" "${ISSUE_LINKS}")
else
  COMMENT="${SUMMARY}"
fi

echo "Posting summary comment on ${ORIGINATING_REPO}#${ORIGINATING_NUMBER}"
# Note: we handle 401/403 inline rather than relying on github-api-csma.sh
# because the intent is different. CSMA retries rate-limited requests; here
# we want graceful degradation when the token permanently lacks permission
# to comment on a specific repo. Retrying a 403 permission error is futile.
COMMENT_OUTPUT=""
COMMENT_EXIT=0
COMMENT_OUTPUT=$(jq -nc --arg body "${COMMENT}" '{body: $body}' | gh api \
  "repos/${ORIGINATING_REPO}/issues/${ORIGINATING_NUMBER}/comments" \
  --input - 2>&1) || COMMENT_EXIT=$?

if [[ ${COMMENT_EXIT} -ne 0 ]]; then
  # Treat 401/403 as non-fatal — the token lacks permission to comment on
  # this repo, but the core deliverables (analysis + proposal issues) are
  # already complete. See #2305.
  # The grep pattern matches gh CLI's "HTTP 4xx" error format. If a future
  # gh version changes the format, the match will fail-closed (treating the
  # error as fatal), which is the safer default.
  if echo "${COMMENT_OUTPUT}" | grep -qE "HTTP (401|403)"; then
    # Sanitize before interpolating into GHA workflow command to prevent
    # injecting ::set-output or ::save-state directives via crafted responses.
    SAFE_OUTPUT="${COMMENT_OUTPUT//::/}"
    SAFE_OUTPUT="${SAFE_OUTPUT//%0A/}"
    SAFE_OUTPUT="${SAFE_OUTPUT//%0a/}"
    SAFE_OUTPUT="${SAFE_OUTPUT//%0D/}"
    SAFE_OUTPUT="${SAFE_OUTPUT//%0d/}"
    echo "::warning::Could not post summary comment to ${ORIGINATING_REPO}#${ORIGINATING_NUMBER}: insufficient permissions (${SAFE_OUTPUT}). Skipping."
  else
    # Sanitize before echoing to prevent GHA workflow command injection
    # (same pattern as the 401/403 branch above).
    SAFE_OUTPUT="${COMMENT_OUTPUT//::/}"
    SAFE_OUTPUT="${SAFE_OUTPUT//%0A/}"
    SAFE_OUTPUT="${SAFE_OUTPUT//%0a/}"
    SAFE_OUTPUT="${SAFE_OUTPUT//%0D/}"
    SAFE_OUTPUT="${SAFE_OUTPUT//%0d/}"
    echo "ERROR: failed to post summary comment on ${ORIGINATING_REPO}#${ORIGINATING_NUMBER}: ${SAFE_OUTPUT}"
    exit 1
  fi
fi

echo "Post-retro complete."
